### ISSUE TITLE
Beta 4 - Discovered universes only shows sacnview

### ISSUE THREAD

**Issue by jmsinick** [docsteer/sacnview#191]
I'm working on a network with 30+ universes and multiple sources, however the only sources I see in the discovered tab are for sacnview and nothing from the rest of the network.  I can even open another sacnview on another pc and it will show up in the first pc discovered view. 

![image](https://user-images.githubusercontent.com/39881409/59079037-81cb2180-88a7-11e9-92a2-e882ba92383e.png)

![image](https://user-images.githubusercontent.com/39881409/59079069-93142e00-88a7-11e9-9e1f-a49e0a52ec0c.png)

**Comment by marcusbirkin** [comment]
sACNView will show devices in the discovered tab that use the special discovery packets added in a later version of the standard.
It's very likely that the other sources on this network only use the early version of the standard with doesn't include the use of this packet type. I certainly only know of two implementations.

What are the other make/model of sources? Are you able to make a wireshark log, I can then double check they aren't utilising this special packet in an incompatible way.

Perhaps the issue here is the labelling in sACNView, I couldn't come up with a clear way of indicating that this is only the special discovery packets...

**Comment by jmsinick** [comment]
Interesting.  Here is a quick capture of the network with only the ACN packets. We have an EOS RPU, a couple pathways gateways and a PACP all transmitting what should be ratified ACN.  

I guess what I was expecting to see with discovered was basically a filtered view of the all tab but only with the active universes.  This site is using a ton of scattered universes (not my choice) and it would be nice to see only the active in a single tab.  Other sites I've seen use 1-10 and then 101-110. 

![image](https://user-images.githubusercontent.com/39881409/59085444-383cff80-88c4-11e9-86dd-cc8ef0a47944.png)

[eos-pathways-pacp.zip](https://github.com/docsteer/sacnview/files/3264688/eos-pathways-pacp.zip)

**Comment by marcusbirkin** [comment]
EOS and P-ACP definitely don't currently send discovery packets.
To the best of my knowledge neither does pathway, certainly in your capture only sACNView is sending them.

The sticking point, and the reason why the standard was extended, is that to discover all the universes with the basic protocol you need to listen to 63,999 universes. Which means opening up 63,999 multicast groups. The process, and quite possibly the OS, would simply grind to a halt. Rough fag packet maths puts this to about 3200 sockets required.
I did try a sort of round robin scanning, but this was hard to get the balance between not choking the OS with socket requests and getting through the universes.

The implemented compromise is that you can expand and contract the number of universes in the "all" tab.

If your interested the wireshark filter for these packets is: "ip.dst == 239.255.250.214".
