### ISSUE TITLE
Portable Windows-Version

### ISSUE THREAD

**Issue by GralfR** [docsteer/sacnview#227]
Hi!
What about a portable compiled version for Windows?
Version 1.3.3 was great as a single exe. In version 2.0 after installation a copy of the directory could be used on different machines if the dependencies were available.
I'd like to have sACNView portable to be able to use it on any (windows-)system without installation.
Is this possible?

Thanks

**Comment by RichardTea** [comment]
This isn't feasible to do with MSVC on Windows anymore because of the way Microsoft maintain the modern MSVC runtimes.
As far as I know, it's no longer possible to statically-link the MSVC runtime, and it's now composed of a few hundred DLLs so it's not feasible (and definitely not supported) 

Copying the installation directory will work if the machine already has an appropriate version of the MSVC redistribution installed. If it doesn't, then you'll need to install the MSVC 2015-2019 redist.
At the moment that installer is actually in the installation directory (although it shouldn't be)

A fully portable mingw build might be possible, I don't know anything about the modern mingw runtime libraries.
If you've got that toolchain and Qt then perhaps give that a try?

**Comment by docsteer** [comment]
As Richard mentions unfortunately this is more and more difficult to do with modern windows applications. I certainly agree it would be nice, but not doable with ease - and I forsee that getting worse in future (I've encountered security problems even running executables on USB drives lately..)

Will bear in mind if Windows does anything to help in future, but not doable right now.
