### ISSUE TITLE
Missing runtime in v2.1.2

### ISSUE THREAD

**Issue by BradenEH** [docsteer/sacnview#235]
I've tried installing v2.1.2 on Windows 10 Pro 1909 but get an error that mvcp140_1.dll is missing on startup.  Uninstalled/reinstalled without any change in behavior.  A cursory internet search indicates a problem with certain versions of MVC++ not including this file.

Issue repeats after updating to v2.1.2.

**Comment by marcusbirkin** [comment]
This is odd, it should auto bundle with the correct version.

Note for later:
v2.1.2 contains MSVC++ 2015-2019 v14.28.9334
v2.1.1 contains MSVC++ 2015 v14.0.24215

**Comment by BradenEH** [comment]
From what I can see - it will work in debug mode, but there seems to be similar challenges with other applications out there, based on what I could find on the web.  One solution was to embed it in the application, but that would probably make it significantly larger.  That is where my knowledge runs thin!

**Comment by RichardTea** [comment]
mvcp140_1.dll is required for Windows applications and DLLs built with MSVC 2019 since around Jan/Feb 2020.
Prior to that date it was an optional component that not all MSVC 2019 applications required.

The Windows 32bit installer does contain the correct version of the 32bit redist, signed by Microsoft in Nov 2020.

It would appear that the redist failed to install on your particular machine.
The most probable issue would be that you don't actually have administrative rights but the installer failed to detect that somehow.

Can you take a look in `C:\Windows\SysWOW64` and see whether you have an `msvcp140_1.dll` there?
If it's present, can you post the version of both `msvcp140.dll` and `msvcp140_1.dll`?

(Right-click, choose Properties, look in the Details tab)

Note: You may also have msvcp140**d**.dll and msvcp140_1**d**.dll. Ignore those!

**Comment by BradenEH** [comment]
msvcp140_1.dll was not present until I installed the previous version, which provided it.

This was on a fresh-out of the box PC.  I tried on another machine and had the similar issues (see below).  Incidentally, on yet another machine that already had other applications installed (i.e. net3 Concert, Paradigm LD), it worked fine.

On the second PC, the following files were reported missing:
MCRUNTIME140.dll
MSVCP140.dll
- I confirmed that these files do not exist in the sysWOW64 folder

**Comment by tw0fer** [comment]
Hey there, I'm having the same missing msvcp140_1.dll issue on Windows 10 Pro 1809. I have checked the SysWOW64 folder and it does not exist.

**Comment by marcusbirkin** [comment]
The 'Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019' be directly downloaded from Microsoft here: https://aka.ms/vs/16/release/vc_redist.x86.exe

This should install the missing runtime

**Comment by docsteer** [comment]
The problem turned out to be that the exact filename of the redistributable changed - fixed and tested on a clean virtual machine. v2.1.3 beta 1 is now released and on the website, and includes this fix.
