### ISSUE TITLE
Source informations visibility

### ISSUE THREAD

**Issue by sstaub** [docsteer/sacnview#265]
If I terminate a source or the source is timed out the source informations stays visible.
Is this intended? Maybe the info line should cleared.

**Comment by RichardTea** [comment]
This is intentional so that you can see every source that has ever been active, and when it was most recently active.

Perhaps the most obvious use case for this is testing with a "slow sending" source. It's important to be able to see that the source did send at all, even if there is a bug that means it is sending too slowly (or perhaps only once!) and thus times out before it sends the next packet.

**Comment by sstaub** [comment]
Ok, I found the online field which helps me to see if a stream is active. So, it is good to know.
